name: A workflow for Fibonacci Serie
on: push

jobs:
  build:
    name: Run the Fibonacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./Fibonacci
        with:
          N_SERIE: 12
